
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '41243F855750D9954F2EB3A18A78E5AA'
    
_lr_action_items = {'$end':([1,2,3,4,5,7,11,12,13,],[-1,-8,-7,0,-5,-3,-2,-6,-4,]),'RPAREN':([2,3,5,7,9,11,12,13,],[-8,-7,-5,-3,12,-2,-6,-4,]),'MULT_OP':([2,3,5,7,11,12,13,],[-8,-7,-5,10,10,-6,-4,]),'FLOAT':([0,6,8,10,],[3,3,3,3,]),'ADD_OP':([1,2,3,5,7,9,11,12,13,],[8,-8,-7,-5,-3,8,-2,-6,-4,]),'LPAREN':([0,6,8,10,],[6,6,6,6,]),'INT':([0,6,8,10,],[2,2,2,2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'arith_expr':([0,6,],[1,9,]),'command':([0,],[4,]),'factor':([0,6,8,10,],[5,5,5,13,]),'term':([0,6,8,],[7,7,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> arith_expr','command',1,'p_command','yaccparser.py',56),
  ('arith_expr -> arith_expr ADD_OP term','arith_expr',3,'p_arith_expr','yaccparser.py',60),
  ('arith_expr -> term','arith_expr',1,'p_arith_expr_term','yaccparser.py',67),
  ('term -> term MULT_OP factor','term',3,'p_term','yaccparser.py',71),
  ('term -> factor','term',1,'p_term_factor','yaccparser.py',79),
  ('factor -> LPAREN arith_expr RPAREN','factor',3,'p_factor','yaccparser.py',83),
  ('factor -> FLOAT','factor',1,'p_factor_float','yaccparser.py',87),
  ('factor -> INT','factor',1,'p_factor_int','yaccparser.py',91),
]
